ALTER TABLE `users`
	ADD COLUMN `price_right` INT(11) NOT NULL DEFAULT '1' AFTER `admin`;
	
CREATE TABLE `orders_po` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`order_id` INT(11) NULL DEFAULT NULL,
	`name` VARCHAR(250) NULL DEFAULT NULL,
	`ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `name_idx` (`name`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;